pipeline {
    agent any

    stages {

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t devops-app ./docker'
            }
        }

        stage('Run Container') {
            steps {
                sh '''
                  docker rm -f devops-app || true
                  docker run -d -p 5000:5000 --name devops-app devops-app
                '''
            }
        }
    }

    post {
        success {
            echo "✅ Pipeline succeeded"
        }
        failure {
            echo "❌ Pipeline failed"
        }
    }
}
