pipeline {
    agent any
    
    options {
        skipDefaultCheckout(true)
    }
    
    stages {
        stage('Clean Workspace') {
            steps {
                deleteDir()  // Native Jenkins step - wipes entire workspace
                echo 'Workspace cleaned'
            }
        }
        
        stage('Checkout Code') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-creds',
                    url: 'https://github.com/jayantidani/aws-devops-production-project.git'
                echo 'Git checkout successful'
            }
        }
        
        stage('Build Docker') {
            steps {
                sh 'docker build -t aws-devops-app .'
            }
        }
        
        stage('Run Container') {
            steps {
                sh 'docker run -d -p 8080:80 --name aws-devops-app aws-devops-app'
            }
        }
    }
    
    post {
        always {
            echo 'Pipeline finished'
        }
    }
}
